;;; hyprland-consult-test.el --- Tests for consult integration -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Code:

(require 'ert)
(require 'hyprland-consult)

(declare-function consult--lookup-cdr "consult" (selected candidates &rest _))

(ert-deftest hyprland-consult-test-state/accepts-direct-action-cand-callback ()
  (should-not (hyprland-consult--state 'setup nil))
  (should-not (hyprland-consult--state 'return nil)))

(ert-deftest hyprland-consult-test-state/return-always-cleans-up ()
  (let (called cancelled)
    (cl-letf (((symbol-function 'hyprland-consult--cleanup-preview)
               (lambda () (setq called t)))
              ((symbol-function 'hyprland-preview-cancel)
               (lambda () (setq cancelled t))))
      (hyprland-consult--state 'return "cand")
      (should called)
      (should cancelled))))

(ert-deftest hyprland-consult-test-state/preview-nil-keeps-existing-preview ()
  (let (called requested)
    (cl-letf (((symbol-function 'hyprland-consult--cleanup-preview)
               (lambda () (setq called t)))
              ((symbol-function 'hyprland-preview-request)
               (lambda (&rest _) (setq requested t))))
      (hyprland-consult--state 'preview nil)
      (should-not called)
      (should-not requested))))

(ert-deftest hyprland-consult-test-state/preview-window-triggers-preview-request ()
  (let* ((window '((address . "0xabc")))
         seen-window)
    (cl-letf (((symbol-function 'hyprland-consult--display-preview) #'ignore)
              ((symbol-function 'hyprland-preview-request)
               (lambda (w _cb) (setq seen-window w))))
      (hyprland-consult--state 'preview window)
      (should (equal seen-window window)))))

(ert-deftest hyprland-consult-test-state/preview-invalid-candidate-shows-message ()
  (let (payload)
    (cl-letf (((symbol-function 'hyprland-consult--display-preview)
               (lambda (p) (setq payload p))))
      (hyprland-consult--state 'preview "label")
      (should payload)
      (should-not (plist-get payload :ok))
      (should (string-match-p "metadata missing" (plist-get payload :message))))))

(ert-deftest hyprland-consult-test-state/exit-cancels-preview-pipeline ()
  (let (cancelled cleaned)
    (cl-letf (((symbol-function 'hyprland-preview-cancel)
               (lambda () (setq cancelled t)))
              ((symbol-function 'hyprland-consult--cleanup-preview)
               (lambda () (setq cleaned t))))
      (hyprland-consult--state 'exit nil)
      (should cancelled)
      (should cleaned))))

(ert-deftest hyprland-consult-test-select-window-candidate/consult-path ()
  (let* ((window '((address . "0xabc")))
         (cands (list (cons "x" window)))
         seen-args)
    (cl-letf (((symbol-function 'hyprland-consult--candidates)
               (lambda () cands))
              ((symbol-function 'consult--read)
               (lambda (table &rest args)
                 (setq seen-args (list table args))
                 window)))
      (should (equal (hyprland--select-window-candidate) window))
      (should (equal (car seen-args) cands))
      (should (eq (plist-get (cadr seen-args) :lookup) #'consult--lookup-cdr))
      (should (eq (plist-get (cadr seen-args) :state) #'hyprland-consult--state))
      (should (equal (plist-get (cadr seen-args) :preview-key)
                     hyprland-consult-preview-key)))))

(ert-deftest hyprland-consult-test-select-window-candidate/no-candidates ()
  (cl-letf (((symbol-function 'hyprland-consult--candidates)
             (lambda () nil))
            ((symbol-function 'consult--read)
             (lambda (&rest _args)
               (ert-fail "consult--read should not run for nil candidates"))))
    (should-not (hyprland--select-window-candidate))))

(provide 'hyprland-consult-test)
;;; hyprland-consult-test.el ends here
