;;; hyprland-preview-test.el --- Tests for hyprland preview -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Code:

(require 'ert)
(require 'hyprland-preview)

(ert-deftest hyprland-preview-test-address-identifier/strip-0x-and-pad ()
  (should (equal (hyprland-preview--address->identifier "0xABC123") "0000000000abc123")))

(ert-deftest hyprland-preview-test-address-identifier/reject-invalid ()
  (should-not (hyprland-preview--address->identifier "xyz-1")))

(ert-deftest hyprland-preview-test-focus-default-disabled ()
  (should-not (default-value 'hyprland-preview-focus-for-accurate-capture)))

(ert-deftest hyprland-preview-test-cache-prune/max-entries ()
  (let ((hyprland-preview--cache (make-hash-table :test #'equal))
        (hyprland-preview--cache-bytes 0)
        (hyprland-preview-cache-max-entries 1)
        (hyprland-preview-cache-max-bytes 100000)
        (hyprland-preview-ttl-seconds 3600)
        (ts 0.0))
    (cl-letf (((symbol-function 'hyprland-preview--now)
               (lambda ()
                 (setq ts (+ ts 1.0))
                 ts)))
      (hyprland-preview--cache-put "a" "aaa")
      (hyprland-preview--cache-put "b" "bbb")
      (should (= (hash-table-count hyprland-preview--cache) 1))
      (should-not (gethash "a" hyprland-preview--cache))
      (should (gethash "b" hyprland-preview--cache)))))

(ert-deftest hyprland-preview-test-cache-get/expired-entry-cleared ()
  (let ((hyprland-preview--cache (make-hash-table :test #'equal))
        (hyprland-preview--cache-bytes 4)
        (hyprland-preview-ttl-seconds 1))
    (puthash "k" (list :ts 0.0 :bytes 4 :png-bytes "data") hyprland-preview--cache)
    (cl-letf (((symbol-function 'hyprland-preview--now) (lambda () 10.0)))
      (should-not (hyprland-preview--cache-get "k"))
      (should-not (gethash "k" hyprland-preview--cache))
      (should (= hyprland-preview--cache-bytes 0)))))

(ert-deftest hyprland-preview-test-capture-args/grim-target ()
  (let ((window '((address . "0xabc"))))
    (should (equal (hyprland-preview--capture-args window)
                   '("-T" "0000000000000abc" "-")))))

(ert-deftest hyprland-preview-test-capture-args/grim-target-with-cursor ()
  (let ((window '((address . "0xabc")))
        (hyprland-preview-overlay-cursor t))
    (should (equal (hyprland-preview--capture-args window)
                   '("-c" "-T" "0000000000000abc" "-")))))

(ert-deftest hyprland-preview-test-capture-args/error-without-address ()
  (let ((window '((title . "x"))))
    (should-error (hyprland-preview--capture-args window))))

(ert-deftest hyprland-preview-test-needs-focus/hidden-window ()
  (let ((window '((hidden . 1))))
    (cl-letf (((symbol-function 'hyprland-preview--active-workspace-id)
               (lambda () 1)))
      (should (hyprland-preview--needs-focus-for-capture-p window)))))

(ert-deftest hyprland-preview-test-needs-focus/workspace-mismatch ()
  (let ((window '((workspace . ((id . 3))))))
    (cl-letf (((symbol-function 'hyprland-preview--active-workspace-id)
               (lambda () 1)))
      (should (hyprland-preview--needs-focus-for-capture-p window)))))

(ert-deftest hyprland-preview-test-restore-focus-dispatches-and-clears ()
  (let ((hyprland-preview--active-restore-address "0xabc")
        seen)
    (cl-letf (((symbol-function 'hyprland--dispatch)
               (lambda (_dispatcher arg) (setq seen arg))))
      (hyprland-preview--restore-focus)
      (should (equal seen "address:0xabc"))
      (should-not hyprland-preview--active-restore-address))))

(ert-deftest hyprland-preview-test-capture-attempts/grim-only ()
  (let ((window '((address . "0xabc"))))
    (cl-letf (((symbol-function 'hyprland-preview--grim-capture-attempt)
               (lambda (_w) '(:backend grim :program "grim" :args ("-T" "0000000000000abc" "-")))))
      (let ((attempts (hyprland-preview--capture-attempts window)))
        (should (equal (length attempts) 1))
        (should (eq (plist-get (car attempts) :backend) 'grim))))))

(ert-deftest hyprland-preview-test-request/startup-error-returns-failure-payload ()
  (let ((window '((address . "0xabc") (at . (1 2)) (size . (3 4))))
        payload)
    (cl-letf (((symbol-function 'hyprland-preview--sensitive-p)
               (lambda (_window) nil))
              ((symbol-function 'hyprland-preview--cache-key)
               (lambda (_window) "k"))
              ((symbol-function 'hyprland-preview--cache-get)
               (lambda (_key) nil))
              ((symbol-function 'hyprland-preview--cancel-active-process)
               #'ignore)
              ((symbol-function 'hyprland-preview--capture-attempts)
               (lambda (_window)
                 '((:backend grim :program "grim" :args ("-T" "0000000000000abc" "-")))))
              ((symbol-function 'make-process)
               (lambda (&rest _args)
                 (error "exec format error"))))
      (hyprland-preview-request window (lambda (result) (setq payload result)))
      (should payload)
      (should-not (plist-get payload :ok))
      (should (eq (plist-get payload :reason) 'capture-failed))
      (should (string-match-p "failed to start" (or (plist-get payload :message) ""))))))

(provide 'hyprland-preview-test)
;;; hyprland-preview-test.el ends here
