;;; hyprland-preview-test.el --- Tests for hyprland preview -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Code:

(require 'ert)
(require 'hyprland-preview)

(ert-deftest hyprland-preview-test-stable-id/number ()
  (should (equal (hyprland-preview--stable-id->identifier 3735928559) "deadbeef")))

(ert-deftest hyprland-preview-test-stable-id/strip-0x ()
  (should (equal (hyprland-preview--stable-id->identifier "0xABC123") "abc123")))

(ert-deftest hyprland-preview-test-stable-id/reject-invalid ()
  (should-not (hyprland-preview--stable-id->identifier "xyz-1")))

(ert-deftest hyprland-preview-test-focus-default-disabled ()
  (should-not (default-value 'hyprland-preview-focus-for-accurate-capture)))

(ert-deftest hyprland-preview-test-geometry/valid ()
  (let ((window '((at . (10 20)) (size . (1920 1080)))))
    (should (equal (hyprland-preview--geometry window) "10,20 1920x1080"))))

(ert-deftest hyprland-preview-test-capture-args/fallback-to-geometry ()
  (let ((window '((stable_id . "oops") (at . (1 2)) (size . (3 4))))
        (hyprland-preview--grim-supports-target nil))
    (cl-letf (((symbol-function 'hyprland-preview--grim-supports-target-p)
               (lambda () nil)))
      (should (equal (hyprland-preview--capture-args window)
                     '("-g" "1,2 3x4" "-"))))))

(ert-deftest hyprland-preview-test-needs-focus/hidden-window ()
  (let ((window '((hidden . 1))))
    (cl-letf (((symbol-function 'hyprland-preview--active-workspace-id)
               (lambda () 1)))
      (should (hyprland-preview--needs-focus-for-capture-p window)))))

(ert-deftest hyprland-preview-test-needs-focus/workspace-mismatch ()
  (let ((window '((workspace . ((id . 3))))))
    (cl-letf (((symbol-function 'hyprland-preview--active-workspace-id)
               (lambda () 1)))
      (should (hyprland-preview--needs-focus-for-capture-p window)))))

(ert-deftest hyprland-preview-test-restore-focus-dispatches-and-clears ()
  (let ((hyprland-preview--active-restore-address "0xabc")
        seen)
    (cl-letf (((symbol-function 'hyprland--dispatch)
               (lambda (_dispatcher arg) (setq seen arg))))
      (hyprland-preview--restore-focus)
      (should (equal seen "address:0xabc"))
      (should-not hyprland-preview--active-restore-address))))

(ert-deftest hyprland-preview-test-capture-attempts/auto-prefers-helper ()
  (let ((window '((address . "0xabc") (at . (1 2)) (size . (3 4))))
        (hyprland-preview-capture-backend 'auto))
    (cl-letf (((symbol-function 'hyprland-preview--toplevel-helper-path)
               (lambda () "/tmp/hyprland-toplevel-snap"))
              ((symbol-function 'hyprland-preview--grim-capture-attempt)
               (lambda (_w) '(:backend grim :program "grim" :args ("-g" "1,2 3x4" "-")))))
      (let ((attempts (hyprland-preview--capture-attempts window)))
        (should (equal (length attempts) 2))
        (should (eq (plist-get (car attempts) :backend) 'toplevel))
        (should (eq (plist-get (cadr attempts) :backend) 'grim))))))

(ert-deftest hyprland-preview-test-capture-attempts/toplevel-only ()
  (let ((window '((address . "0xabc")))
        (hyprland-preview-capture-backend 'toplevel))
    (cl-letf (((symbol-function 'hyprland-preview--toplevel-helper-path)
               (lambda () "/tmp/hyprland-toplevel-snap")))
      (let ((attempts (hyprland-preview--capture-attempts window)))
        (should (equal (length attempts) 1))
        (should (eq (plist-get (car attempts) :backend) 'toplevel))))))

(ert-deftest hyprland-preview-test-capture-attempts/grim-only ()
  (let ((window '((at . (1 2)) (size . (3 4))))
        (hyprland-preview-capture-backend 'grim))
    (cl-letf (((symbol-function 'hyprland-preview--grim-capture-attempt)
               (lambda (_w) '(:backend grim :program "grim" :args ("-g" "1,2 3x4" "-")))))
      (let ((attempts (hyprland-preview--capture-attempts window)))
        (should (equal (length attempts) 1))
        (should (eq (plist-get (car attempts) :backend) 'grim))))))

(ert-deftest hyprland-preview-test-toplevel-helper-path/reject-empty-local-file ()
  (let* ((tmp (make-temp-file "hyprland-preview-test" t))
         (root (expand-file-name "pkg" tmp))
         (tools (expand-file-name "tools" root))
         (lib (expand-file-name "hyprland-preview.el" root))
         (helper (expand-file-name "hyprland-toplevel-snap" tools))
         (hyprland-preview-toplevel-helper-executable "hyprland-toplevel-snap"))
    (make-directory tools t)
    (with-temp-file lib)
    (with-temp-file helper)
    (set-file-modes helper #o755)
    (unwind-protect
        (cl-letf (((symbol-function 'executable-find) (lambda (_exe) nil))
                  ((symbol-function 'locate-library) (lambda (_name) lib)))
          (should-not (hyprland-preview--toplevel-helper-path)))
      (delete-directory tmp t))))

(ert-deftest hyprland-preview-test-request/startup-error-returns-failure-payload ()
  (let ((window '((address . "0xabc") (at . (1 2)) (size . (3 4))))
        payload)
    (cl-letf (((symbol-function 'hyprland-preview--sensitive-p)
               (lambda (_window) nil))
              ((symbol-function 'hyprland-preview--cache-key)
               (lambda (_window) "k"))
              ((symbol-function 'hyprland-preview--cache-get)
               (lambda (_key) nil))
              ((symbol-function 'hyprland-preview--cancel-active-process)
               #'ignore)
              ((symbol-function 'hyprland-preview--capture-attempts)
               (lambda (_window)
                 '((:backend toplevel :program "broken-helper" :args ("--foo")))))
              ((symbol-function 'make-process)
               (lambda (&rest _args)
                 (error "exec format error"))))
      (hyprland-preview-request window (lambda (result) (setq payload result)))
      (should payload)
      (should-not (plist-get payload :ok))
      (should (eq (plist-get payload :reason) 'capture-failed))
      (should (string-match-p "failed to start" (or (plist-get payload :message) ""))))))

(provide 'hyprland-preview-test)
;;; hyprland-preview-test.el ends here
