;;; hyprland-zen-test.el --- Tests for Zen bridge -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'hyprland-zen)

(defvar hyprland-zen-test--refresh-count 0)

(defun hyprland-zen-test--count-refresh ()
  "Increment refresh counter for hook tests."
  (setq hyprland-zen-test--refresh-count (1+ hyprland-zen-test--refresh-count)))

(ert-deftest hyprland-zen-test-tab-key/defaults ()
  (should (equal (hyprland-zen--tab-key '((tab_id . 42)))
                 "zen/default/42")))

(ert-deftest hyprland-zen-test-workspace-key/defaults ()
  (should (equal (hyprland-zen--workspace-key '((workspace_id . "main")))
                 "zen/default/main")))

(ert-deftest hyprland-zen-test-apply-message/snapshot-upsert-remove ()
  (let ((hyprland-zen--tabs (make-hash-table :test #'equal))
        (hyprland-zen--workspaces (make-hash-table :test #'equal))
        (hyprland-zen-after-refresh-hook '(hyprland-zen-test--count-refresh))
        (hyprland-zen-test--refresh-count 0))
    (hyprland-zen--apply-message
     '((type . "snapshot")
       (tabs . (((browser . "zen") (profile . "main") (tab_id . "1") (title . "A"))
                ((browser . "zen") (profile . "main") (tab_id . "2") (title . "B"))))))
    (should (= (hash-table-count hyprland-zen--tabs) 2))
    (should (= hyprland-zen-test--refresh-count 1))

    (hyprland-zen--apply-message
     '((type . "upsert")
       (tab . ((browser . "zen") (profile . "main") (tab_id . "1") (title . "A2")))))
    (should (equal (hyprland-zen--field (hyprland-zen-tab-get "zen/main/1") 'title) "A2"))
    (should (= hyprland-zen-test--refresh-count 2))

    (hyprland-zen--apply-message
     '((type . "remove")
       (key . "zen/main/1")))
    (should-not (hyprland-zen-tab-get "zen/main/1"))
    (should (= (hash-table-count hyprland-zen--tabs) 1))
    (should (= hyprland-zen-test--refresh-count 3))))

(ert-deftest hyprland-zen-test-apply-message/workspace-upsert-remove ()
  (let ((hyprland-zen--workspaces (make-hash-table :test #'equal))
        (hyprland-zen-after-refresh-hook '(hyprland-zen-test--count-refresh))
        (hyprland-zen-test--refresh-count 0))
    (hyprland-zen--apply-message
     '((type . "workspace_snapshot")
       (workspaces . (((browser . "zen") (profile . "main") (workspace_id . "a") (name . "A"))
                      ((browser . "zen") (profile . "main") (workspace_id . "b") (name . "B"))))))
    (should (= (hash-table-count hyprland-zen--workspaces) 2))
    (should (= hyprland-zen-test--refresh-count 1))

    (hyprland-zen--apply-message
     '((type . "workspace-upsert")
       (workspace . ((browser . "zen") (profile . "main") (workspace_id . "a") (name . "AA") (active . t)))))
    (should (equal (hyprland-zen--field (hyprland-zen-workspace-get "zen/main/a") 'name) "AA"))
    (should (hyprland-zen--field (hyprland-zen-workspace-get "zen/main/a") 'active))
    (should (= hyprland-zen-test--refresh-count 2))

    (hyprland-zen--apply-message
     '((type . "workspace-remove")
       (key . "zen/main/a")))
    (should-not (hyprland-zen-workspace-get "zen/main/a"))
    (should (= (hash-table-count hyprland-zen--workspaces) 1))
    (should (= hyprland-zen-test--refresh-count 3))))

(ert-deftest hyprland-zen-test-store-tab/derives-workspace ()
  (let ((hyprland-zen--tabs (make-hash-table :test #'equal))
        (hyprland-zen--workspaces (make-hash-table :test #'equal)))
    (hyprland-zen--store-tab '((browser . "zen")
                               (profile . "main")
                               (workspace_id . "w1")
                               (workspace_name . "WS1")
                               (tab_id . "12")
                               (title . "T")))
    (should (hyprland-zen-workspace-get "zen/main/w1"))
    (should (equal (hyprland-zen--field (hyprland-zen-workspace-get "zen/main/w1") 'name)
                   "WS1"))))

(ert-deftest hyprland-zen-test-process-filter/line-buffering ()
  (let ((hyprland-zen--fragment "")
        seen)
    (cl-letf (((symbol-function 'hyprland-zen--handle-line)
               (lambda (line) (push line seen))))
      (hyprland-zen--process-filter nil "{\"type\":\"snapshot\"}\n{\"type\":\"up")
      (should (equal (nreverse seen) '("{\"type\":\"snapshot\"}")))
      (should (equal hyprland-zen--fragment "{\"type\":\"up"))
      (setq seen nil)
      (hyprland-zen--process-filter nil "sert\"}\n")
      (should (equal (nreverse seen) '("{\"type\":\"upsert\"}")))
      (should (string-empty-p hyprland-zen--fragment)))))

(ert-deftest hyprland-zen-test-send/encodes-json-line ()
  (let ((hyprland-zen--process 'proc)
        (hyprland-zen--messages-out 0)
        sent)
    (cl-letf (((symbol-function 'process-live-p)
               (lambda (proc) (eq proc 'proc)))
              ((symbol-function 'process-send-string)
               (lambda (_proc string) (setq sent string))))
      (hyprland-zen--send '((op . "list-tabs")))
      (should (= hyprland-zen--messages-out 1))
      (should (string-match-p "\"op\":\"list-tabs\"" sent))
      (should (string-suffix-p "\n" sent)))))

(ert-deftest hyprland-zen-test-apply-message/error-updates-diagnostics ()
  (let ((hyprland-zen--messages-in 0)
        (hyprland-zen--last-line-type nil)
        (hyprland-zen--last-error-message nil)
        (hyprland-zen--last-error-op nil))
    (hyprland-zen--apply-message
     '((type . "error")
       (op . "capture-tab")
       (message . "capture failed")))
    (should (= hyprland-zen--messages-in 1))
    (should (equal hyprland-zen--last-line-type "error"))
    (should (equal hyprland-zen--last-error-op "capture-tab"))
    (should (equal hyprland-zen--last-error-message "capture failed"))))

(ert-deftest hyprland-zen-test-status/reports-current-diagnostics ()
  (let ((hyprland-zen--process 'proc)
        (hyprland-zen--tabs (make-hash-table :test #'equal))
        (hyprland-zen--workspaces (make-hash-table :test #'equal))
        (hyprland-zen--messages-in 5)
        (hyprland-zen--messages-out 7)
        (hyprland-zen--last-line-type "snapshot")
        (hyprland-zen--last-error-message "none")
        report)
    (puthash "zen/default/1" '((tab_id . "1")) hyprland-zen--tabs)
    (puthash "zen/default/w" '((workspace_id . "w")) hyprland-zen--workspaces)
    (cl-letf (((symbol-function 'process-live-p)
               (lambda (proc) (eq proc 'proc)))
              ((symbol-function 'process-id)
               (lambda (_proc) 4242))
              ((symbol-function 'hyprland-zen--seconds-since)
               (lambda (_timestamp) 0.5)))
      (setq report (hyprland-zen-status)))
    (should (plist-get report :running))
    (should (= (plist-get report :pid) 4242))
    (should (= (plist-get report :tab-count) 1))
    (should (= (plist-get report :workspace-count) 1))
    (should (= (plist-get report :messages-in) 5))
    (should (= (plist-get report :messages-out) 7))
    (should (equal (plist-get report :last-message-type) "snapshot"))))

(ert-deftest hyprland-zen-test-doctor/returns-readiness-report ()
  (let (started refreshed refreshed-workspaces)
    (cl-letf (((symbol-function 'hyprland-zen-running-p)
               (lambda () nil))
              ((symbol-function 'hyprland-zen-start)
               (lambda () (setq started t)))
              ((symbol-function 'hyprland-zen-refresh)
               (lambda () (setq refreshed t)))
              ((symbol-function 'hyprland-zen-refresh-workspaces)
               (lambda () (setq refreshed-workspaces t)))
              ((symbol-function 'hyprland-zen--wait-for-tabs)
               (lambda (&optional _timeout) '(((tab_id . "1")))))
              ((symbol-function 'hyprland-zen--ensure-workspaces-ready)
               (lambda () '(((workspace_id . "w")))))
              ((symbol-function 'hyprland-zen-status)
               (lambda () '(:running t :tab-count 1 :workspace-count 1))))
      (let ((report (hyprland-zen-doctor 2.0)))
        (should started)
        (should refreshed)
        (should refreshed-workspaces)
        (should (= (plist-get report :wait-time) 2.0))
        (should (plist-get report :tabs-ready))
        (should (plist-get report :workspaces-ready))
        (should (plist-get report :running))))))

(ert-deftest hyprland-zen-test-ensure-tabs-ready/starts-and-refreshes-empty-store ()
  (let ((hyprland-zen--tabs (make-hash-table :test #'equal))
        started refreshed refreshed-workspaces)
    (cl-letf (((symbol-function 'hyprland-zen-running-p)
               (lambda () nil))
              ((symbol-function 'hyprland-zen-start)
               (lambda () (setq started t)))
              ((symbol-function 'hyprland-zen-refresh)
               (lambda () (setq refreshed t)))
              ((symbol-function 'hyprland-zen-refresh-workspaces)
               (lambda () (setq refreshed-workspaces t)))
              ((symbol-function 'hyprland-zen--wait-for-tabs)
               (lambda (&optional _timeout)
                 (list '((tab_id . "1"))))))
      (should (equal (hyprland-zen--ensure-tabs-ready)
                     '(((tab_id . "1")))))
      (should started)
      (should refreshed)
      (should refreshed-workspaces))))

(ert-deftest hyprland-zen-test-ensure-workspaces-ready/refreshes-empty-store ()
  (let ((hyprland-zen--workspaces (make-hash-table :test #'equal))
        (hyprland-zen--process 'proc)
        refreshed)
    (cl-letf (((symbol-function 'hyprland-zen-running-p)
               (lambda () t))
              ((symbol-function 'hyprland-zen-refresh-workspaces)
               (lambda ()
                 (setq refreshed t)
                 (puthash "zen/default/w" '((workspace_id . "w")) hyprland-zen--workspaces)))
              ((symbol-function 'accept-process-output)
               (lambda (&rest _args) t)))
      (should (equal (hyprland-zen--ensure-workspaces-ready)
                     '(((workspace_id . "w")))))
      (should refreshed))))

(ert-deftest hyprland-zen-test-apply-message/preview-dispatches-active-request ()
  (let ((hyprland-zen--preview-tab-id "7")
        seen-url)
    (cl-letf (((symbol-function 'hyprland-zen--display-preview-data-url)
               (lambda (url) (setq seen-url url))))
      (hyprland-zen--apply-message
       '((type . "preview")
         (tab_id . "7")
         (image_data_url . "data:image/png;base64,AA==")))
      (should (equal seen-url "data:image/png;base64,AA==")))))

(ert-deftest hyprland-zen-test-apply-message/preview-ignores-stale-tab ()
  (let ((hyprland-zen--preview-tab-id "7")
        seen-url)
    (cl-letf (((symbol-function 'hyprland-zen--display-preview-data-url)
               (lambda (url) (setq seen-url url))))
      (hyprland-zen--apply-message
       '((type . "preview")
         (tab_id . "8")
         (image_data_url . "data:image/png;base64,AA==")))
      (should-not seen-url))))

(ert-deftest hyprland-zen-test-preview-state/requests-capture ()
  (let (payload message)
    (cl-letf (((symbol-function 'hyprland-zen--send)
               (lambda (msg) (setq payload msg)))
              ((symbol-function 'hyprland-zen--display-preview-message)
               (lambda (msg) (setq message msg))))
      (hyprland-zen--preview-state 'preview '((tab_id . "99")))
      (should (equal hyprland-zen--preview-tab-id "99"))
      (should (equal message "Loading tab preview..."))
      (should (equal (hyprland-zen--field payload 'op) "capture-tab"))
      (should (equal (hyprland-zen--field payload 'tab_id) "99")))))

(ert-deftest hyprland-zen-test-preview-state/resolves-string-candidate-via-lookup ()
  (let ((hyprland-zen--preview-candidates
         '(("A" . ((tab_id . "42") (title . "A")))))
        payload
        message)
    (cl-letf (((symbol-function 'consult--lookup-cdr)
               (lambda (selected candidates _input)
                 (cdr (assoc selected candidates))))
              ((symbol-function 'hyprland-zen--send)
               (lambda (msg) (setq payload msg)))
              ((symbol-function 'hyprland-zen--display-preview-message)
               (lambda (msg) (setq message msg))))
      (hyprland-zen--preview-state 'preview "A")
      (should (equal hyprland-zen--preview-tab-id "42"))
      (should (equal message "Loading tab preview..."))
      (should (equal (hyprland-zen--field payload 'tab_id) "42")))))

(ert-deftest hyprland-zen-test-preview-state/exit-cleans-up ()
  (let ((hyprland-zen--preview-tab-id "11")
        (hyprland-zen--preview-candidates '(("A" . ((tab_id . "1")))))
        cleaned)
    (cl-letf (((symbol-function 'hyprland-consult--cleanup-preview)
               (lambda () (setq cleaned t))))
      (hyprland-zen--preview-state 'exit nil)
      (should cleaned)
      (should-not hyprland-zen--preview-tab-id)
      (should-not hyprland-zen--preview-candidates))))

(ert-deftest hyprland-zen-test-resolve-host-command/prefers-path ()
  (let ((hyprland-zen-host-command '("hyprland-zen-native-host" "--line-stdio")))
    (cl-letf (((symbol-function 'executable-find)
               (lambda (_cmd) "/usr/bin/hyprland-zen-native-host"))
              ((symbol-function 'hyprland-zen--usable-executable-p)
               (lambda (_path) t)))
      (should (equal (hyprland-zen--resolve-host-command)
                     '("/usr/bin/hyprland-zen-native-host" "--line-stdio"))))))

(ert-deftest hyprland-zen-test-resolve-host-command/falls-back-local-script ()
  (let ((hyprland-zen-host-command '("hyprland-zen-native-host" "--line-stdio"))
        seen)
    (cl-letf (((symbol-function 'executable-find)
               (lambda (_cmd) nil))
              ((symbol-function 'locate-library)
               (lambda (_lib) "/repo/hyprland-zen.el"))
              ((symbol-function 'hyprland-zen--usable-executable-p)
               (lambda (path)
                 (setq seen path)
                 (and (stringp path)
                      (string-match-p "browser/native-host/hyprland-zen-native-host$" path)))))
      (should (equal (hyprland-zen--resolve-host-command)
                     '("/repo/browser/native-host/hyprland-zen-native-host" "--line-stdio")))
      (should (string-match-p "browser/native-host/hyprland-zen-native-host$" seen)))))

(ert-deftest hyprland-zen-test-tab-switch/sends-activate-command ()
  (let ((tab '((browser . "zen") (profile . "default") (tab_id . "9")))
        payload)
    (cl-letf (((symbol-function 'hyprland-zen--read-tab)
               (lambda (_prompt) tab))
              ((symbol-function 'hyprland-zen--send)
               (lambda (msg) (setq payload msg))))
      (should (equal (hyprland-zen-tab-switch) "zen/default/9"))
      (should (equal (hyprland-zen--field payload 'op) "activate-tab"))
      (should (equal (hyprland-zen--field payload 'key) "zen/default/9")))))

(ert-deftest hyprland-zen-test-start/starts-process-and-refreshes ()
  (let ((hyprland-zen-host-command '("host" "--stdio"))
        (hyprland-zen-auto-refresh-on-start t)
        (hyprland-zen--process nil)
        launched refreshed refreshed-workspaces)
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (setq launched args)
                 'proc))
              ((symbol-function 'hyprland-zen--resolve-host-command)
               (lambda () '("host" "--stdio")))
              ((symbol-function 'hyprland-zen-refresh)
               (lambda () (setq refreshed t)))
              ((symbol-function 'hyprland-zen-refresh-workspaces)
               (lambda () (setq refreshed-workspaces t))))
      (should (eq (hyprland-zen-start) 'proc))
      (should (equal (plist-get launched :command) '("host" "--stdio")))
      (should refreshed)
      (should refreshed-workspaces))))

(ert-deftest hyprland-zen-test-workspace-switch/sends-activate-command ()
  (let ((workspace '((browser . "zen") (profile . "default") (workspace_id . "w9")))
        payload)
    (cl-letf (((symbol-function 'hyprland-zen--read-workspace)
               (lambda (_prompt) workspace))
              ((symbol-function 'hyprland-zen--send)
               (lambda (msg) (setq payload msg))))
      (should (equal (hyprland-zen-workspace-switch) "zen/default/w9"))
      (should (equal (hyprland-zen--field payload 'op) "activate-workspace"))
      (should (equal (hyprland-zen--field payload 'key) "zen/default/w9")))))

(ert-deftest hyprland-zen-test-mode/toggles-start-stop ()
  (let (started stopped)
    (unwind-protect
        (cl-letf (((symbol-function 'hyprland-zen-start)
                   (lambda () (setq started t)))
                  ((symbol-function 'hyprland-zen-stop)
                   (lambda () (setq stopped t))))
          (hyprland-zen-mode 1)
          (hyprland-zen-mode 0)
          (should started)
          (should stopped))
      (setq hyprland-zen-mode nil))))

(provide 'hyprland-zen-test)
;;; hyprland-zen-test.el ends here
