;;; hyprland-preview-test.el --- Tests for hyprland preview -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Code:

(require 'ert)
(require 'hyprland-preview)

(ert-deftest hyprland-preview-test-cache-prune/max-entries ()
  (let ((hyprland-preview--cache (make-hash-table :test #'equal))
        (hyprland-preview--cache-bytes 0)
        (hyprland-preview-cache-max-entries 1)
        (hyprland-preview-cache-max-bytes 100000)
        (hyprland-preview-ttl-seconds 3600)
        (ts 0.0))
    (cl-letf (((symbol-function 'hyprland-preview--now)
               (lambda ()
                 (setq ts (+ ts 1.0))
                 ts)))
      (hyprland-preview--cache-put "a" "aaa")
      (hyprland-preview--cache-put "b" "bbb")
      (should (= (hash-table-count hyprland-preview--cache) 1))
      (should-not (gethash "a" hyprland-preview--cache))
      (should (gethash "b" hyprland-preview--cache)))))

(ert-deftest hyprland-preview-test-cache-get/expired-entry-cleared ()
  (let ((hyprland-preview--cache (make-hash-table :test #'equal))
        (hyprland-preview--cache-bytes 4)
        (hyprland-preview-ttl-seconds 1))
    (puthash "k" (list :ts 0.0 :bytes 4 :png-bytes "data") hyprland-preview--cache)
    (cl-letf (((symbol-function 'hyprland-preview--now) (lambda () 10.0)))
      (should-not (hyprland-preview--cache-get "k"))
      (should-not (gethash "k" hyprland-preview--cache))
      (should (= hyprland-preview--cache-bytes 0)))))

(ert-deftest hyprland-preview-test-capture-command/toplevel-helper ()
  (let ((window '((address . "0xabc"))))
    (cl-letf (((symbol-function 'hyprland-preview--toplevel-helper-path)
               (lambda () "/tmp/hyprland-toplevel-snap")))
      (let ((cmd (hyprland-preview--capture-command window)))
        (should (equal (plist-get cmd :program) "/tmp/hyprland-toplevel-snap"))
        (should (equal (plist-get cmd :args) '("--address" "0xabc")))))))

(ert-deftest hyprland-preview-test-toplevel-helper-path/reject-empty-local-file ()
  (let* ((tmp (make-temp-file "hyprland-preview-test" t))
         (root (expand-file-name "pkg" tmp))
         (tools (expand-file-name "tools" root))
         (lib (expand-file-name "hyprland-preview.el" root))
         (helper (expand-file-name "hyprland-toplevel-snap" tools))
         (hyprland-preview-toplevel-helper-executable "hyprland-toplevel-snap"))
    (make-directory tools t)
    (with-temp-file lib)
    (with-temp-file helper)
    (set-file-modes helper #o755)
    (unwind-protect
        (cl-letf (((symbol-function 'executable-find) (lambda (_exe) nil))
                  ((symbol-function 'locate-library) (lambda (_name) lib)))
          (should-not (hyprland-preview--toplevel-helper-path)))
      (delete-directory tmp t))))

(ert-deftest hyprland-preview-test-request/startup-error-returns-failure-payload ()
  (let ((window '((address . "0xabc") (at . (1 2)) (size . (3 4))))
        payload)
    (cl-letf (((symbol-function 'hyprland-preview--sensitive-p)
               (lambda (_window) nil))
              ((symbol-function 'hyprland-preview--cache-key)
               (lambda (_window) "k"))
              ((symbol-function 'hyprland-preview--cache-get)
               (lambda (_key) nil))
              ((symbol-function 'hyprland-preview--cancel-active-process)
               #'ignore)
              ((symbol-function 'hyprland-preview--capture-command)
               (lambda (_window)
                 '(:program "broken-helper" :args ("--foo"))))
              ((symbol-function 'make-process)
               (lambda (&rest _args)
                 (error "exec format error"))))
      (hyprland-preview-request window (lambda (result) (setq payload result)))
      (should payload)
      (should-not (plist-get payload :ok))
      (should (eq (plist-get payload :reason) 'capture-failed))
      (should (string-match-p "failed to start" (or (plist-get payload :message) ""))))))

(provide 'hyprland-preview-test)
;;; hyprland-preview-test.el ends here
